### ISSUE TITLE
adoc escaping problems in source code: angle brackets

### ISSUE THREAD

**Issue by anarthal** [cppalliance/mrdocs#763] opened 2024-12-06 13:29 UTC
The following generates problems:

```cpp

#include <type_traits>

namespace repro {

/// A type trait.
template <class T>
struct trait
{
    /// The actual value.
    static constexpr bool value = std::is_same_v<T, int> || std::is_same_v<T, float>;
};

}  // namespace repro

int main() {}
```

For `repro/trait/value.adoc`, it generates:

```adoc
= Reference
:mrdocs:

[#repro-trait-value]
== xref:../../repro.adoc[repro]::xref:../trait.adoc[trait]::value


The actual value.


=== Synopsis

Declared in `<pass:[main.cpp]>`
[source,cpp,subs="verbatim,macros,-callouts"]
----
constexpr
static
bool const value = pass:[std::is_same_v<T, int> || std::is_same_v<T, float>];
----



[.small]#Created with https://www.mrdocs.com[MrDocs]#
```

Which renders as:

![Image](https://github.com/user-attachments/assets/c94b5d55-214c-4180-ab15-7e6e2c0b1f18)

I'm worried that we're trying to solve an unsolvable problem, as the lack of a robust escaping strategy has been an open issue in asciidoc for 10 years (https://github.com/asciidoctor/asciidoctor/issues/901).

**Comment by alandefreitas** [comment] 2024-12-06 14:04
Here's the relevant code:

https://github.com/cppalliance/mrdocs/blob/e41d78032306eef1c5af91fc31ee6e1224dd1e68/src/lib/Gen/adoc/AdocGenerator.cpp#L35-L58

The only way I see to solve this problem consistently is for HTML to escape whatever goes inside `pass`. This has the obvious disadvantage of coupling the asciidoc output format to HTML. 

An alternative would be to try to escape as much as possible with `\` and only use a `pass` block as a last resort. The difficulty here is that commands chars must be escaped only in their opening tags and only when there's a corresponding closing tag. For instance, 

- `_a_` renders as `<em>a</em>` (the usual case)
- `\_a_` renders as `_a_` (usual escaping)
- `_a\_` renders as `<em>a\</em>` (no escaping the opening tag)
- `_a` renders as `_a` (command not applied because there's no closing tag)
- `\_a` renders as `\_a` (command not escaped because there's no closing tag)

In this case, it would have to be a more complex algorithm that keeps track of the context so that we know what kind of commands we are escaping. There's also a weird problem of precedence between commands:

- `*_a_*` renders as `<strong><em>a</em></strong>` (the usual case)
- `_*a*_` renders as `<em>*a*</em>` (`*` is not effective because it's inside `_`)
- `\*_a_*` renders as `*<em>a</em>*` (`*` is properly escaped and `_` is applied)
- `\_*a*_` renders as `\_*a*_` (`_` is escaped and `*` is not applied because it's inside `_` even though it's escaped)
- `_\*a*_` renders as `<em>\*a*</em>` (no escaping because `*` is not effective inside `_`)
- `*\_a_*` renders as `<strong>_a_</strong>` (it does escape because `_` is effective inside `*`)

I don't even know how to achieve `_<strong>a</strong>_` because in `_*a*_` the `*` passes through regardless of whether `_` is escaped.

So, we must identify "effective" opening tags by examining the current context and looking ahead to ensure the tag is closing somewhere. Whenever in a command context, we can't try to escape anything else.

It's a complex algorithm that would evolve with time. However, now that I'm thinking more about it, escaping HTML inside pass is not such a bad idea because by using pass, the content is coupled with the output format anyway. It's just coupled in a way that's not what we want for any output format (such as literal `<`s for HTML). So the problem is not that we shouldn't escape HTML content in `pass`. The problem is we should try to never use `pass` at all.

**Comment by alandefreitas** [comment] 2024-12-06 18:31
Another thing we could implement here is making the `pass` block apply only to consecutive characters that need it. For now, we apply `pass` to everything because it looked cleaner on the output, but being more precise gives us more correct output.

**Comment by alandefreitas** [comment] 2024-12-11 19:39
I just did a small experiment with nested commands. The results are almost random. Sometimes, `\` escapes the nested command. Sometimes it doesn't. It should be an unexpected effect of the way regex is applied. 

But at least we can identify what should be escaped based on the context.

```adoc
Nested formatters

_a_, _#a#_, _*a*_, _`a`_, _~a~_, _^a^_, _[[a]]_, _{a}_, _<<a>>_

#_a_#, #a#, #*a*#, #`a`#, #~a~#, #^a^#, #[[a]]#, #{a}#, #<<a>>#

*_a_*, *#a#*, *a*, *`a`*, *~a~*, *^a^*, *[[a]]*, *{a}*, *<<a>>*

`_a_`, `#a#`, `*a*`, `a`, `~a~`, `^a^`, `[[a]]`, `{a}`, `<<a>>`

~_a_~, ~#a#~, ~*a*~, ~`a`~, ~a~, ~^a^~, ~[[a]]~, ~{a}~, ~<<a>>~

^_a_^, ^#a#^, ^*a*^, ^`a`^, ^~a~^, ^a^, ^[[a]]^, ^{a}^, ^<<a>>^

[[_a_]], [[#a#]], [[*a*]], [[`a`]], [[~a~]], [[^a^]], [[a]], [[{a}]], [[<<a>>]]

{_a_}, {#a#}, {*a*}, {`a`}, {~a~}, {^a^}, {[[a]]}, {a}, {<<a>>}

<<_a_>>, <<#a#>>, <<*a*>>, <<`a`>>, <<~a~>>, <<^a^>>, <<[[a]]>>, <<{a}>>, <<a>>

Escape outter

\_a_, \_#a#_, \_*a*_, \_`a`_, \_~a~_, \_^a^_, \_[[a]]_, \_{a}_, \_<<a>>_

\#_a_#, \#a#, \#*a*#, \#`a`#, \#~a~#, \#^a^#, \#[[a]]#, \#{a}#, \#<<a>>#

\*_a_*, \*#a#*, \*a*, \*`a`*, \*~a~*, \*^a^*, \*[[a]]*, \*{a}*, \*<<a>>*

\`_a_`, \`#a#`, \`*a*`, \`a`, \`~a~`, \`^a^`, \`[[a]]`, \`{a}`, \`<<a>>`

\~_a_~, \~#a#~, \~*a*~, \~`a`~, \~a~, \~^a^~, \~[[a]]~, \~{a}~, \~<<a>>~

\^_a_^, \^#a#^, \^*a*^, \^`a`^, \^~a~^, \^a^, \^[[a]]^, \^{a}^, \^<<a>>^

\[[_a_]], \[[#a#]], \[[*a*]], \[[`a`]], \[[~a~]], \[[^a^]], \[[a]], \[[{a}]], \[[<<a>>]]

\{_a_}, \{#a#}, \{*a*}, \{`a`}, \{~a~}, \{^a^}, \{[[a]]}, \{a}, \{<<a>>}

\<<_a_>>, \<<#a#>>, \<<*a*>>, \<<`a`>>, \<<~a~>>, \<<^a^>>, \<<[[a]]>>, \<<{a}>>, \<<a>>

Escape inner

_a_, _\#a#_, _\*a*_, _\`a`_, _\~a~_, _\^a^_, _\[[a]]_, _\{a}_, _\<<a>>_

#\_a_#, #a#, #\*a*#, #\`a`#, #\~a~#, #\^a^#, #\[[a]]#, #\{a}#, #\<<a>>#

*\_a_*, *\#a#*, *a*, *\`a`*, *\~a~*, *\^a^*, *\[[a]]*, *\{a}*, *\<<a>>*

`\_a_`, `\#a#`, `\*a*`, `a`, `\~a~`, `\^a^`, `\[[a]]`, `\{a}`, `\<<a>>`

~\_a_~, ~\#a#~, ~\*a*~, ~\`a`~, ~a~, ~\^a^~, ~\[[a]]~, ~\{a}~, ~\<<a>>~

^\_a_^, ^\#a#^, ^\*a*^, ^\`a`^, ^\~a~^, ^a^, ^\[[a]]^, ^\{a}^, ^\<<a>>^

[[\_a_]], [[\#a#]], [[\*a*]], [[\`a`]], [[\~a~]], [[\^a^]], [[a]], [[\{a}]], [[\<<a>>]]

{\_a_}, {\#a#}, {\*a*}, {\`a`}, {\~a~}, {\^a^}, {\[[a]]}, {a}, {\<<a>>}

<<\_a_>>, <<\#a#>>, <<\*a*>>, <<\`a`>>, <<\~a~>>, <<\^a^>>, <<\[[a]]>>, <<\{a}>>, <<a>>

Escape both

\_a_, \_\#a#_, \_\*a*_, \_\`a`_, \_\~a~_, \_\^a^_, \_\[[a]]_, \_\{a}_, \_\<<a>>_

\#\_a_#, \#a#, \#\*a*#, \#\`a`#, \#\~a~#, \#\^a^#, \#\[[a]]#, \#\{a}#, \#\<<a>>#

\*\_a_*, \*\#a#*, \*a*, \*\`a`*, \*\~a~*, \*\^a^*, \*\[[a]]*, \*\{a}*, \*\<<a>>*

\`\_a_`, \`\#a#`, \`\*a*`, \`a`, \`\~a~`, \`\^a^`, \`\[[a]]`, \`\{a}`, \`\<<a>>`

\~\_a_~, \~\#a#~, \~\*a*~, \~\`a`~, \~a~, \~\^a^~, \~\[[a]]~, \~\{a}~, \~\<<a>>~

\^\_a_^, \^\#a#^, \^\*a*^, \^\`a`^, \^\~a~^, \^a^, \^\[[a]]^, \^\{a}^, \^\<<a>>^

\[[\_a_]], \[[\#a#]], \[[\*a*]], \[[\`a`]], \[[\~a~]], \[[\^a^]], \[[a]], \[[\{a}]], \[[\<<a>>]]

\{\_a_}, \{\#a#}, \{\*a*}, \{\`a`}, \{\~a~}, \{\^a^}, \{\[[a]]}, \{a}, \{\<<a>>}

\<<\_a_>>, \<<\#a#>>, \<<\*a*>>, \<<\`a`>>, \<<\~a~>>, \<<\^a^>>, \<<\[[a]]>>, \<<\{a}>>, \<<a>>
```

And here are the results:

<div id="content">
<div class="paragraph">
<p>Nested formatters</p>
</div>
<div class="paragraph">
<p><em>a</em>, <em><mark>a</mark></em>, <em>*a*</em>, <em>`a`</em>, <em><sub>a</sub></em>, <em><sup>a</sup></em>, <em><a id="a"></a></em>, <em>{a}</em>, <em><a href="#a">[a]</a></em></p>
</div>
<div class="paragraph">
<p><mark><em>a</em></mark>, <mark>a</mark>, <mark><strong>a</strong></mark>, <mark><code>a</code></mark>, <mark><sub>a</sub></mark>, <mark><sup>a</sup></mark>, <mark><a id="a"></a></mark>, <mark>{a}</mark>, <mark><a href="#a">[a]</a></mark></p>
</div>
<div class="paragraph">
<p><strong><em>a</em></strong>, <strong><mark>a</mark></strong>, <strong>a</strong>, <strong><code>a</code></strong>, <strong><sub>a</sub></strong>, <strong><sup>a</sup></strong>, <strong><a id="a"></a></strong>, <strong>{a}</strong>, <strong><a href="#a">[a]</a></strong></p>
</div>
<div class="paragraph">
<p><code><em>a</em></code>, <code><mark>a</mark></code>, <code><strong>a</strong></code>, <code>a</code>, <code><sub>a</sub></code>, <code><sup>a</sup></code>, <code><a id="a"></a></code>, <code>{a}</code>, <code><a href="#a">[a]</a></code></p>
</div>
<div class="paragraph">
<p><sub><em>a</em></sub>, <sub><mark>a</mark></sub>, <sub><strong>a</strong></sub>, <sub><code>a</code></sub>, <sub>a</sub>, <sub><sup>a</sup></sub>, <sub><a id="a"></a></sub>, <sub>{a}</sub>, <sub><a href="#a">[a]</a></sub></p>
</div>
<div class="paragraph">
<p><sup><em>a</em></sup>, <sup><mark>a</mark></sup>, <sup><strong>a</strong></sup>, <sup><code>a</code></sup>, <sup><sub>a</sub></sup>, <sup>a</sup>, <sup><a id="a"></a></sup>, <sup>{a}</sup>, <sup><a href="#a">[a]</a></sup></p>
</div>
<div class="paragraph">
<p>[[<em>a</em>]], [[<mark>a</mark>]], [[<strong>a</strong>]], [[<code>a</code>]], [[<sub>a</sub>]], [[<sup>a</sup>]], <a id="a"></a>, [[{a}]], [[<a href="#a">[a]</a>]]</p>
</div>
<div class="paragraph">
<p>{<em>a</em>}, {<mark>a</mark>}, {<strong>a</strong>}, {<code>a</code>}, {<sub>a</sub>}, {<sup>a</sup>}, {<a id="a"></a>}, {a}, {<a href="#a">[a]</a>}</p>
</div>
<div class="paragraph">
<p><a href="#_a_">[_a_]</a>, <a href="#a#">[a#]</a>, &lt;&lt;*a*&gt;&gt;, &lt;&lt;`a`&gt;&gt;, &lt;&lt;<sub>a</sub>&gt;&gt;, &lt;&lt;<sup>a</sup>&gt;&gt;, &lt;&lt;<a id="a"></a>&gt;&gt;, <a href="#{a}">[{a}]</a>, <a href="#a">[a]</a></p>
</div>
<div class="paragraph">
<p>Escape outter</p>
</div>
<div class="paragraph">
<p>_a_, _#a#_, _*a*_, _`a`_, _<sub>a</sub>_, _<sup>a</sup>_, _<a id="a"></a>_, _{a}_, _<a href="#a">[a]</a>_</p>
</div>
<div class="paragraph">
<p>#<em>a</em>#, #a#, #<strong>a</strong>#, #<code>a</code>#, #<sub>a</sub>#, #<sup>a</sup>#, #<a id="a"></a>#, #{a}#, #<a href="#a">[a]</a>#</p>
</div>
<div class="paragraph">
<p>*<em>a</em>*, *<mark>a</mark>*, *a*, *<code>a</code>*, *<sub>a</sub>*, *<sup>a</sup>*, *<a id="a"></a>*, *{a}*, *<a href="#a">[a]</a>*</p>
</div>
<div class="paragraph">
<p>`<em>a</em>`, `<mark>a</mark>`, `<strong>a</strong>`, `a`, `<sub>a</sub>`, `<sup>a</sup>`, `<a id="a"></a>`, `{a}`, `<a href="#a">[a]</a>`</p>
</div>
<div class="paragraph">
<p>~<em>a</em>~, ~<mark>a</mark>~, ~<strong>a</strong>~, ~<code>a</code>~, ~a~, ~<sup>a</sup>~, ~<a id="a"></a>~, ~{a}~, ~<a href="#a">[a]</a>~</p>
</div>
<div class="paragraph">
<p>^<em>a</em>^, ^<mark>a</mark>^, ^<strong>a</strong>^, ^<code>a</code>^, ^<sub>a</sub>^, ^a^, ^<a id="a"></a>^, ^{a}^, ^<a href="#a">[a]</a>^</p>
</div>
<div class="paragraph">
<p>\[[<em>a</em>]], \[[<mark>a</mark>]], \[[<strong>a</strong>]], \[[<code>a</code>]], \[[<sub>a</sub>]], \[[<sup>a</sup>]], [[a]], \[[{a}]], \[[<a href="#a">[a]</a>]]</p>
</div>
<div class="paragraph">
<p>\{<em>a</em>}, \{<mark>a</mark>}, \{<strong>a</strong>}, \{<code>a</code>}, \{<sub>a</sub>}, \{<sup>a</sup>}, \{<a id="a"></a>}, {a}, \{<a href="#a">[a]</a>}</p>
</div>
<div class="paragraph">
<p>&lt;&lt;_a_&gt;&gt;, &lt;&lt;#a#&gt;&gt;, \&lt;&lt;*a*&gt;&gt;, \&lt;&lt;`a`&gt;&gt;, \&lt;&lt;<sub>a</sub>&gt;&gt;, \&lt;&lt;<sup>a</sup>&gt;&gt;, \&lt;&lt;<a id="a"></a>&gt;&gt;, &lt;&lt;{a}&gt;&gt;, &lt;&lt;a&gt;&gt;</p>
</div>
<div class="paragraph">
<p>Escape inner</p>
</div>
<div class="paragraph">
<p><em>a</em>, <em>#a#</em>, <em>\*a*</em>, <em>\`a`</em>, <em>~a~</em>, <em>^a^</em>, <em>[[a]]</em>, <em>{a}</em>, <em>&lt;&lt;a&gt;&gt;</em></p>
</div>
<div class="paragraph">
<p><mark>_a_</mark>, <mark>a</mark>, <mark>*a*</mark>, <mark>`a`</mark>, <mark>~a~</mark>, <mark>^a^</mark>, <mark>[[a]]</mark>, <mark>{a}</mark>, <mark>&lt;&lt;a&gt;&gt;</mark></p>
</div>
<div class="paragraph">
<p><strong>_a_</strong>, <strong>#a#</strong>, <strong>a</strong>, <strong>`a`</strong>, <strong>~a~</strong>, <strong>^a^</strong>, <strong>[[a]]</strong>, <strong>{a}</strong>, <strong>&lt;&lt;a&gt;&gt;</strong></p>
</div>
<div class="paragraph">
<p><code>_a_</code>, <code>#a#</code>, <code>*a*</code>, <code>a</code>, <code>~a~</code>, <code>^a^</code>, <code>[[a]]</code>, <code>{a}</code>, <code>&lt;&lt;a&gt;&gt;</code></p>
</div>
<div class="paragraph">
<p><sub>_a_</sub>, <sub>#a#</sub>, <sub>*a*</sub>, <sub>`a`</sub>, <sub>a</sub>, <sub>^a^</sub>, <sub>[[a]]</sub>, <sub>{a}</sub>, <sub>&lt;&lt;a&gt;&gt;</sub></p>
</div>
<div class="paragraph">
<p><sup>_a_</sup>, <sup>#a#</sup>, <sup>*a*</sup>, <sup>`a`</sup>, <sup>~a~</sup>, <sup>a</sup>, <sup>[[a]]</sup>, <sup>{a}</sup>, <sup>&lt;&lt;a&gt;&gt;</sup></p>
</div>
<div class="paragraph">
<p><a id="_a_"></a>, [[#a#]], [[*a*]], [[`a`]], [[~a~]], [[^a^]], <a id="a"></a>, [[{a}]], [[&lt;&lt;a&gt;&gt;]]</p>
</div>
<div class="paragraph">
<p>{_a_}, {#a#}, {*a*}, {`a`}, {~a~}, {^a^}, {[[a]]}, {a}, {&lt;&lt;a&gt;&gt;}</p>
</div>
<div class="paragraph">
<p><a href="#_a_">[_a_]</a>, <a href="#a#">[a#]</a>, &lt;&lt;*a*&gt;&gt;, &lt;&lt;`a`&gt;&gt;, &lt;&lt;~a~&gt;&gt;, &lt;&lt;^a^&gt;&gt;, &lt;&lt;[[a]]&gt;&gt;, <a href="#{a}">[{a}]</a>, <a href="#a">[a]</a></p>
</div>
<div class="paragraph">
<p>Escape both</p>
</div>
<div class="paragraph">
<p>_a_, _\#a#_, _\*a*_, _\`a`_, _~a~_, _^a^_, _[[a]]_, _{a}_, _&lt;&lt;a&gt;&gt;_</p>
</div>
<div class="paragraph">
<p>#_a_#, #a#, #*a*#, #`a`#, #~a~#, #^a^#, #[[a]]#, #{a}#, #&lt;&lt;a&gt;&gt;#</p>
</div>
<div class="paragraph">
<p>*_a_*, *#a#*, *a*, *`a`*, *~a~*, *^a^*, *[[a]]*, *{a}*, *&lt;&lt;a&gt;&gt;*</p>
</div>
<div class="paragraph">
<p>`_a_`, `#a#`, `*a*`, `a`, `~a~`, `^a^`, `[[a]]`, `{a}`, `&lt;&lt;a&gt;&gt;`</p>
</div>
<div class="paragraph">
<p>~_a_~, ~#a#~, ~*a*~, ~`a`~, ~a~, ~^a^~, ~[[a]]~, ~{a}~, ~&lt;&lt;a&gt;&gt;~</p>
</div>
<div class="paragraph">
<p>^_a_^, ^#a#^, ^*a*^, ^`a`^, ^~a~^, ^a^, ^[[a]]^, ^{a}^, ^&lt;&lt;a&gt;&gt;^</p>
</div>
<div class="paragraph">
<p>[[_a_]], \[[#a#]], \[[*a*]], \[[`a`]], \[[~a~]], \[[^a^]], [[a]], \[[{a}]], \[[&lt;&lt;a&gt;&gt;]]</p>
</div>
<div class="paragraph">
<p>{_a_}, \{#a#}, \{*a*}, \{`a`}, \{~a~}, \{^a^}, \{[[a]]}, {a}, \{&lt;&lt;a&gt;&gt;}</p>
</div>
<div class="paragraph">
<p>&lt;&lt;_a_&gt;&gt;, &lt;&lt;#a#&gt;&gt;, \&lt;&lt;*a*&gt;&gt;, \&lt;&lt;`a`&gt;&gt;, \&lt;&lt;~a~&gt;&gt;, \&lt;&lt;^a^&gt;&gt;, \&lt;&lt;[[a]]&gt;&gt;, &lt;&lt;{a}&gt;&gt;, &lt;&lt;a&gt;&gt;</p>
</div>
</div>

**Closed** 2024-12-13 14:02 UTC
