### ISSUE TITLE
Command line option --output takes paths not relative to cwd

### ISSUE THREAD

**Issue by anarthal** [cppalliance/mrdocs#529] opened 2024-01-03 09:58 UTC
When running
```
mrdocs ... --output=dir
```

`dir` is interpreted relative to the config file, and not to `cwd`. This is a confusing setting, since no other tool does that.

**Comment by alandefreitas** [comment] 2024-05-14 20:36
Doesn't doxygen do that?

**Comment by fpelliccioni** [comment] 2024-06-03 18:44
> Command line option --output now takes paths relative to cwd #571

 I've tested doxygen and couldn't find a way to pass the output directory as an argument to the executable. What doxygen does support is specifying the `OUTPUT_DIRECTORY` in the config file. I can confirm that the output directory in doxygen is relative to the directory where doxygen is run, not the directory where the config file is located.

**Comment by alandefreitas** [comment] 2024-06-03 23:03
IIRC, the Doxygen command is `-s OUTPUT_DIRECTORY=...`, and it overrides whatever comes from the `Doxyfile.` In this case, any path specified in the command line simply overrides the value in the Doxyfile and should also be relative to it. 

Paths are relative to mrdocs.yml because mrdocs.yml is at a stable location in the project. Requiring all relative paths to be relative to cwd doesn't seem like a good idea because it would be extremely verbose, the relative values in mrdocs.yml wouldn't match the command line arguments which would keep changing according to cwd, and creating an exception for `output` would make it even more confusing. 

We can just close this issue, and this behavior should be better documented.

**Comment by alandefreitas** [comment] 2024-06-04 11:58
Obsoleted by #617

**Closed by alandefreitas** 2024-06-04 11:58 UTC
Labels: Bug, Feature
